export const STORE_FETCHED_PAGES = "STORE_FETECHED_PAGES";
export const PAGES_LOADED = "PAGES_LOADED";
export const STORE_FETCHED_PAGE = "STORE_FETCHED_PAGE";
export const GET_FETCHED_PAGE = "GET_FETECHED_PAGE";

export const SHOW_LOADER = "SHOW_LOADER";

export const INCREMENT_LOADING_PROGRESS = "INCREMENT_LOADING_PROGRESS";
export const RESET_LOADING_PROGRESS = "RESET_LOADING_PROGRESS";

export const GET_SITE_DETAILS = "GET_SITE_DETAILS";
